@apiAsistencia = http://localhost:3000/asistencia

###
POST {{apiAsistencia}}/39
Content-Type: application/json

{
    "nombre_usuario": "i89rtjgs",
    "password": "rtttdgflqp"
}

###
POST {{apiAsistencia}}/39
Content-Type: application/json

{
    "nombre_usuario": "i85ijioe",
    "password": "qvmyzybadh"
}
