@apiAsistencia = http://localhost:3000/asistencia

###
POST {{apiAsistencia}}/4
Content-Type: application/json

{
    "nombre_usuario": "i81cdtwj",
    "password": "qexzistiqm"
}

###
POST {{apiAsistencia}}/4
Content-Type: application/json

{
    "nombre_usuario": "i93ujmrg",
    "password": "grrgyijnvd"
}
