
@apiAulas = http://localhost:3000/aulas

###
GET http://localhost:3000/grados

###
GET http://localhost:3000/2/asignaturas

###
GET {{apiAulas}}

###
GET {{apiAulas}}/2/2022-12-06

###
GET {{apiAulas}}/2/2022-12-01/2022-12-31

###
GET {{apiAulas}}/2/Sistemas interactivos/2022-12-01/2022-12-31