
@apiAulas = http://localhost:3000/aulas

###
GET http://localhost:3000/grados

###
GET http://localhost:3000/2/asignaturas

###
GET {{apiAulas}}

###
GET {{apiAulas}}/2022-10-31

###
GET {{apiAulas}}/2022-10-31/2022-12-15

###
GET {{apiAulas}}/Seguridad Informatica/2022-10-31/2023-12-03